### ISSUE TITLE
wrong wording in policy template

### ISSUE THREAD

**Issue by zvr** [OpenChain-Project/curriculum#14]
As @StefaniePors remarked privately, the open source policy template, in sheet "Example Appendix 1" contains a license analysis example that includes the attribute "Commercial Use" (column K).
The explanatory comment for this comment is (emphasis added):

> Does the licence *prohibit* commercial use? 

Given that most of the entries for the licenses are "yes", the explanation should probably be phrased differently...

**Comment by andrewjskatz** [comment]
Good spot! I'm not sure how best to amend this: are you able to do that? It should read 'Commercial Use Permitted'.  Also, the entry against the eCos license should also read 'yes' in the Commercial Use column. 

Thanks


Andrew

**Comment by mkurzman** [comment]
Hi,
I just come from a discussion about the two following trainings offered in the Linux Academy:
LFC191 https://training.linuxfoundation.org/training/compliance-basics-for-developers/#overview and
LFC210 Fundamentals of professional open source management

Does anyone know if and ,if yes, to what extent the Open Chain Curriculum material was used as base to create those trainings?
Is there an overview of all trainings in the Linux Academy vs. which part of the Open Chain Curriculum was covered by it and the other way round?
I would appreciate an overview of training suppliers (for ideally web-based trainings paid or for free) that cover the contents of the curriculum at least in parts, so that I potentially can recommend it to people.

On the other hand, my question for the Linux Academy would be, if changes that are introduced are also updated in the offered trainings. So is there a process?

Thank you for a short feedback if anyone knows.

Mit freundlichen Grüßen / Best regards

Marcel Kurzmann

Open Source Services - Product Group Customer Success Services (INST-CSS/BSV-OS)
Bosch Software Innovations GmbH | Ziegelei 7 | 88090 Immenstaad | GERMANY | www.bosch-si.com<http://www.bosch-si.com>
Tel. +49 7545 202-279 | Mobil +49 172 1499942 | Fax +49 7545 202-301 | marcel.kurzmann@bosch-si.com<mailto:marcel.kurzmann@bosch-si.com>

Sitz: Berlin, Registergericht: Amtsgericht Charlottenburg; HRB 148411 B
Aufsichtsratsvorsitzender: Dr.-Ing. Thorsten Lücke; Geschäftsführung: Dr. Stefan Ferber, Michael Hahn, Dr. Aleksandar Mitrovic
